force-app/main/default/objects/Case/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Journal_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Journal_Status__c</fullName>
    <description>Depicts the journal status of the conversation note. By default no journal entry is created.</description>
    <label>Journal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Journaled</fullName>
                <default>true</default>
                <label>Not Journaled</label>
            </value>
            <value>
                <fullName>Journal Error</fullName>
            </value>
            <value>
                <fullName>Journal Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Object used to reflect a journal entry that has been sent to JOARK.</description>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{0000}</displayFormat>
        <label>Journal Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/objects/Journal_Entry__c/fields/CRM_Conversation_Note__c.field-meta.xml
<CustomField>
    <fullName>CRM_Conversation_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a conversation note if the journal entry is related to this.</description>
    <label>Conversation Note</label>
    <referenceTo>Conversation_Note__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a thread if the journal entry is related to this.</description>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_API_Reference__c.field-meta.xml
<CustomField>
    <fullName>CRM_API_Reference__c</fullName>
    <description>Record reference that is exposed via API</description>
    <externalId>true</externalId>
    <label>API Reference</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/RestServices/CRM_HenvendelseJournalRestService_Test.cls
@isTest
public class CRM_HenvendelseJournalRestService_Test {
    @TestSetup
    static void makeData() {
        CRM_HENV_TestDataFactory.createRecord(new Common_Code__c(CRM_Code_Set__c = 'Tema', CRM_Code__c = 'DAG'));
        CRM_HENV_TestDataFactory.createRecord(new Conversation_Note__c(CRM_Conversation_Note__c = 'DUMMY TEXT'));
        Thread__c thread = (Thread__c) CRM_HENV_TestDataFactory.createRecord(new Thread__c());
        CRM_HENV_TestDataFactory.createRecord(new Message__c(CRM_Thread__c = thread.Id));
    }

    @isTest
    static void testConvNoteJournal() {
        Conversation_Note__c convNote = [SELECT Id, CRM_API_Reference__c FROM Conversation_Note__c LIMIT 1];
        ApiMock.setTestMock('POST_CREATE_JOURNAL', 200, 'OK');

        CRM_HenvendelseJournalRestService.HenvendelseJournalRequest journalReq = new CRM_HenvendelseJournalRestService.HenvendelseJournalRequest();
        journalReq.journalforendeEnhet = '4100';
        journalReq.fagsakId = '123CASE';
        journalReq.temakode = 'DAG;';
        journalReq.kjedeId = convNote.CRM_API_Reference__c;

        RestRequest restReq = new RestRequest();
        restReq.headers.put('X-Correlation-ID', '123RANDOM');
        restReq.headers.put('X-ACTING-NAV-IDENT', 'Z999999');
        restReq.requestBody = Blob.valueOf(JSON.serialize(journalReq));

        RestContext.request = restReq;
        RestContext.response = new RestResponse();

        List<Id> fixedSearchResults = new List<Id>();
        fixedSearchResults.add(convNote.Id);
        //Setting the SOSL fixed search results
        Test.setFixedSearchResults(fixedSearchResults);
        Test.startTest();
        CRM_HenvendelseJournalRestService.createJournalPost();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
        Conversation_Note__c updatedConvNote = [
            SELECT Id, CRM_Journal_Status__c
            FROM Conversation_Note__c
            WHERE Id = :convNote.Id
        ];
        System.assert(updatedConvNote.CRM_Journal_Status__c.equalsIgnoreCase('Journal Completed'));
    }

    @isTest
    static void testThreadJournal() {
        Thread__c thread = [SELECT Id, CRM_API_Reference__c FROM Thread__c LIMIT 1];
        ApiMock.setTestMock('POST_CREATE_JOURNAL', 200, 'OK');

        CRM_HenvendelseJournalRestService.HenvendelseJournalRequest journalReq = new CRM_HenvendelseJournalRestService.HenvendelseJournalRequest();
        journalReq.journalforendeEnhet = '4100';
        journalReq.fagsakId = '123CASE';
        journalReq.temakode = 'DAG;';
        journalReq.kjedeId = thread.CRM_API_Reference__c;

        RestRequest restReq = new RestRequest();
        restReq.headers.put('X-Correlation-ID', '123RANDOM');
        restReq.headers.put('X-ACTING-NAV-IDENT', 'Z999999');
        restReq.requestBody = Blob.valueOf(JSON.serialize(journalReq));

        RestContext.request = restReq;
        RestContext.response = new RestResponse();

        List<Id> fixedSearchResults = new List<Id>();
        fixedSearchResults.add(thread.Id);
        //Setting the SOSL fixed search results
        Test.setFixedSearchResults(fixedSearchResults);
        Test.startTest();
        CRM_HenvendelseJournalRestService.createJournalPost();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
        System.assertNotEquals(0, [SELECT COUNT() FROM Journal_Entry__c WHERE CRM_Thread__c = :thread.Id]);
    }

    @isTest
    static void testInvalidObjectIdInput() {
        ApiMock.setTestMock('POST_CREATE_JOURNAL', 200, 'OK');

        CRM_HenvendelseJournalRestService.HenvendelseJournalRequest journalReq = new CRM_HenvendelseJournalRestService.HenvendelseJournalRequest();
        journalReq.journalforendeEnhet = '4100';
        journalReq.fagsakId = '123CASE';
        journalReq.temakode = 'DAG;';
        journalReq.kjedeId = (String) CRM_HENV_TestDataFactory.createRecord(new Case()).get('Id');

        RestRequest restReq = new RestRequest();
        restReq.headers.put('X-Correlation-ID', '123RANDOM');
        restReq.headers.put('X-ACTING-NAV-IDENT', 'Z999999');
        restReq.requestBody = Blob.valueOf(JSON.serialize(journalReq));

        RestContext.request = restReq;
        RestContext.response = new RestResponse();

        Test.startTest();
        CRM_HenvendelseJournalRestService.createJournalPost();
        Test.stopTest();

        System.assertEquals(400, RestContext.response.statusCode);
    }

    @isTest
    static void testInvalidId() {
        ApiMock.setTestMock('POST_CREATE_JOURNAL', 200, 'OK');

        CRM_HenvendelseJournalRestService.HenvendelseJournalRequest journalReq = new CRM_HenvendelseJournalRestService.HenvendelseJournalRequest();
        journalReq.journalforendeEnhet = '4100';
        journalReq.fagsakId = '123CASE';
        journalReq.temakode = 'DAG;';
        journalReq.kjedeId = '123INVALIDID';

        RestRequest restReq = new RestRequest();
        restReq.headers.put('X-Correlation-ID', '123RANDOM');
        restReq.headers.put('X-ACTING-NAV-IDENT', 'Z999999');
        restReq.requestBody = Blob.valueOf(JSON.serialize(journalReq));

        RestContext.request = restReq;
        RestContext.response = new RestResponse();

        Test.startTest();
        CRM_HenvendelseJournalRestService.createJournalPost();
        Test.stopTest();

        System.assertEquals(400, RestContext.response.statusCode);
    }

    @isTest
    static void testMissingXcorrelation() {
        ApiMock.setTestMock('POST_CREATE_JOURNAL', 200, 'OK');

        CRM_HenvendelseJournalRestService.HenvendelseJournalRequest journalReq = new CRM_HenvendelseJournalRestService.HenvendelseJournalRequest();
        journalReq.journalforendeEnhet = '4100';
        journalReq.fagsakId = '123CASE';
        journalReq.temakode = 'DAG;';
        journalReq.kjedeId = '123INVALIDID';

        RestRequest restReq = new RestRequest();
        restReq.headers.put('X-ACTING-NAV-IDENT', 'Z999999');
        restReq.requestBody = Blob.valueOf(JSON.serialize(journalReq));

        RestContext.request = restReq;
        RestContext.response = new RestResponse();

        Test.startTest();
        CRM_HenvendelseJournalRestService.createJournalPost();
        Test.stopTest();

        System.assertEquals(400, RestContext.response.statusCode);
    }
}