force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Created_By_Ident__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_Ident__c</fullName>
    <description>NAV ident of the user creating the conversation note.</description>
    <externalId>true</externalId>
    <label>Created By</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Created_By_NAV_Unit__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_NAV_Unit__c</fullName>
    <description>NAV unit of the user creating the conversation note.</description>
    <externalId>true</externalId>
    <label>Created By</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/core-functionality/objects/Conversation_Note__c/fields/CRM_Registered_Datetime_Formula__c.field-meta.xml
<CustomField>
    <fullName>CRM_Registered_Datetime_Formula__c</fullName>
    <description>Returns the date and time the conversation note was created. For data which was migrated this results in the timestamp from the Date time registered field, after migration this defaults to system timestamps.</description>
    <formula>IF(ISBLANK(CRM_Date_Time_Registered__c),
			 CreatedDate,
			 CRM_Date_Time_Registered__c
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered Datetime Formula</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_External_Message__c.field-meta.xml
<CustomField>
    <fullName>CRM_External_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_Ident_Formula__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_Ident_Formula__c</fullName>
    <description>For messages migrated that were sent from NAV employees without a Salesforce user, the CRM_From_Ident__c field will store the from information. Messages created in Salesforce will be connected to either a community user or internal user. Returns the external users actor id if the message is from external.</description>
    <formula>IF( CRM_From__c != null,
    (IF( CRM_From__r.ContactId != null,
		CRM_From__r.Contact.Account.CRM_Person__r.INT_ActorId__c,
		CRM_From__r.CRM_NAV_Ident__c 
	)),
	CRM_From_Ident__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>From Ident Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_NAV_Unit__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_NAV_Unit__c</fullName>
    <description>NAV unit number of the user sending the message</description>
    <externalId>true</externalId>
    <label>From NAV Unit</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>CRM_Message_Text__c</fullName>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Sent_Datetime_Formula__c.field-meta.xml
<CustomField>
    <fullName>CRM_Sent_Datetime_Formula__c</fullName>
    <description>Returns the date and time the message was created. For data which was migrated this results in the timestamp from the Date time registered field, after migration this defaults to system timestamps.</description>
    <formula>IF(ISBLANK(CRM_Sent_date__c),
			 CreatedDate,
			 CRM_Sent_date__c
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered Datetime Formula</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/RestServices/API-wrappers/CRM_Melding.cls
global class CRM_Melding extends CRM_HenvendelseApiUtils {
    global enum Communication_Channel {
        TELEFON,
        OPPMOTE,
        DIGITAL
    }

    global CRM_MessageFrom fra;
    global String fritekst;
    global String sendtDato;
    global String lestDato;
    global String kanal;
    global String henvendelseId; //Legacy ID for verification purposes

    global CRM_Melding(Message__c message) {
        this.fritekst = message.CRM_Message_Text__c;
        this.sendtDato = formatDateTime(message.CRM_Sent_Datetime_Formula__c);
        this.lestDato = formatDateTime(message.CRM_Read_Datetime__c);
        this.kanal = Communication_Channel.DIGITAL.name();

        this.fra = new CRM_MessageFrom();
        this.fra.identType = message.CRM_External_Message__c == true
            ? CRM_MessageFrom.IDENT_TYPES.AKTORID.name()
            : CRM_MessageFrom.IDENT_TYPES.NAVIDENT.name();
        this.fra.ident = message.CRM_From_Ident_Formula__c;
        this.fra.navEnhet = message.CRM_From_NAV_Unit__c;
    }

    global CRM_Melding(Conversation_Note__c convNote) {
        this.fritekst = convNote.CRM_Conversation_Note__c;
        this.lestDato = formatDateTime(convNote.CRM_Read_Date__c);
        this.sendtDato = formatDateTime(convNote.CRM_Registered_Datetime_Formula__c);
        if (String.isNotBlank(convNote.CRM_Communication_Channel__c)) {
            this.kanal = convNote.CRM_Communication_Channel__c.equalsIgnoreCase('Phone')
                ? Communication_Channel.TELEFON.name()
                : Communication_Channel.OPPMOTE.name();
        }
        this.fra = new CRM_MessageFrom();
        //Conversation notes are always created by NAV employees
        this.fra.identType = CRM_MessageFrom.IDENT_TYPES.NAVIDENT.name();
        this.fra.ident = convNote.CRM_Created_By_Ident__c;
        this.fra.navEnhet = convNote.CRM_Created_By_NAV_Unit__c;
    }
}