force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Object used to reflect a journal entry that has been sent to JOARK.</description>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{0000}</displayFormat>
        <label>Journal Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/objects/Journal_Entry__c/fields/CRM_Conversation_Note__c.field-meta.xml
<CustomField>
    <fullName>CRM_Conversation_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a conversation note if the journal entry is related to this.</description>
    <label>Conversation Note</label>
    <referenceTo>Conversation_Note__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Journal_Entry_Status__c.field-meta.xml
<CustomField>
    <fullName>Journal_Entry_Status__c</fullName>
    <description>Status of the journal entry submission to JOARK</description>
    <label>Journal Entry Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/NAV_Case_Reference__c.field-meta.xml
<CustomField>
    <fullName>NAV_Case_Reference__c</fullName>
    <description>Unique reference to a NAV case in a legacy system</description>
    <label>NAV Case Reference</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to common code for the theme the journal entry was given.</description>
    <label>Theme</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Common_Code__c.CRM_Code_Set__c</field>
            <operation>equals</operation>
            <value>Tema</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Common_Code__c</referenceTo>
    <relationshipLabel>Journal Entries (Theme)</relationshipLabel>
    <relationshipName>Journal_Entries_Theme</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/core-functionality/classes/CRM_ConvNoteJournalRetryBatch_Test.cls
@isTest
public class CRM_ConvNoteJournalRetryBatch_Test {
    @TestSetup
    static void makeData() {
        Conversation_Note__c convNote = (Conversation_Note__c) CRM_HENV_TestDataFactory.createRecord(
            new Conversation_Note__c()
        );
        Common_Code__c aapCode = (Common_Code__c) CRM_HENV_TestDataFactory.createRecord(
            new Common_Code__c(CRM_Code__c = 'AAP', CRM_Code_Set__c = 'Tema', CRM_Active__c = true)
        );

        Journal_Entry__c je1 = new Journal_Entry__c(
            CRM_Conversation_Note__c = convNote.Id,
            Journal_Entry_Status__c = 'Failed',
            Theme__c = aapCode.Id,
            NAV_Case_Reference__c = '123TEST'
        );
        Journal_Entry__c je2 = new Journal_Entry__c(
            CRM_Conversation_Note__c = convNote.Id,
            Journal_Entry_Status__c = 'Failed',
            Theme__c = aapCode.Id,
            NAV_Case_Reference__c = '456TEST'
        );
        List<Journal_Entry__c> jeList = new List<Journal_Entry__c>{ je1, je2 };
        CRM_HENV_TestDataFactory.createRecordList(jeList);
    }

    @isTest
    static void testJournalRetry() {
        ApiMock.setTestMock('POST_CREATE_JOURNAL', 200, 'OK');

        Test.startTest();
        CRM_ConvNoteJournalRetryBatch.initJournalBatcher();
        Test.stopTest();

        System.assertEquals(2, [SELECT COUNT() FROM Journal_Entry__c WHERE Journal_Entry_Status__c = 'Completed']);
    }
}