force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Created_By_Ident__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_Ident__c</fullName>
    <description>NAV ident of the user creating the conversation note.</description>
    <externalId>true</externalId>
    <label>Created By</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Created_By_NAV_Unit__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_NAV_Unit__c</fullName>
    <description>NAV unit of the user creating the conversation note.</description>
    <externalId>true</externalId>
    <label>Created By</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Object used to reflect a journal entry that has been sent to JOARK.</description>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{0000}</displayFormat>
        <label>Journal Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/objects/Journal_Entry__c/fields/CRM_Conversation_Note__c.field-meta.xml
<CustomField>
    <fullName>CRM_Conversation_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a conversation note if the journal entry is related to this.</description>
    <label>Conversation Note</label>
    <referenceTo>Conversation_Note__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Created_By_Ident__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_Ident__c</fullName>
    <description>NAV ident of the user who created the journal entry.</description>
    <externalId>true</externalId>
    <label>Created By Ident</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Created_By_NAV_Unit__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_NAV_Unit__c</fullName>
    <description>NAV unit number of the user creating the journal entry.</description>
    <externalId>true</externalId>
    <label>Created By NAV Unit</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_NAV_Case_Legacy_System__c.field-meta.xml
<CustomField>
    <fullName>CRM_NAV_Case_Legacy_System__c</fullName>
    <description>If case type = FAGSAK, this defines which legacy system that handles the case. Required for journal purposes using Dokarkiv API</description>
    <label>NAV Case Legacy System</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Subtheme_Code__c.field-meta.xml
<CustomField>
    <fullName>CRM_Subtheme_Code__c</fullName>
    <description>Unique subtheme code</description>
    <formula>Subtheme__r.CRM_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subtheme Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Theme_Code__c.field-meta.xml
<CustomField>
    <fullName>CRM_Theme_Code__c</fullName>
    <description>The unique code from common codes</description>
    <formula>Theme__r.CRM_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Theme Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Journal_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Journal_Entry_ID__c</fullName>
    <description>Unique identifier to a JOARK journal post.</description>
    <externalId>true</externalId>
    <label>Journal Entry ID</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Journal_Entry_Status__c.field-meta.xml
<CustomField>
    <fullName>Journal_Entry_Status__c</fullName>
    <description>Status of the journal entry submission to JOARK</description>
    <label>Journal Entry Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/NAV_Case_Reference__c.field-meta.xml
<CustomField>
    <fullName>NAV_Case_Reference__c</fullName>
    <description>Unique reference to a NAV case in a legacy system</description>
    <label>NAV Case Reference</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Subtheme__c.field-meta.xml
<CustomField>
    <fullName>Subtheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to common code for the subtheme the journal entry was given.</description>
    <label>Subtheme</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Common_Code__c.CRM_Code_Set__c</field>
            <operation>equals</operation>
            <value>Behandlingstema</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Common_Code__c</referenceTo>
    <relationshipLabel>Journal Entries (Subtheme)</relationshipLabel>
    <relationshipName>Journal_Entries_Subtheme</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to common code for the theme the journal entry was given.</description>
    <label>Theme</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Common_Code__c.CRM_Code_Set__c</field>
            <operation>equals</operation>
            <value>Tema</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Common_Code__c</referenceTo>
    <relationshipLabel>Journal Entries (Theme)</relationshipLabel>
    <relationshipName>Journal_Entries_Theme</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CRM_ConvNoteJournalRetryBatch.cls
public without sharing class CRM_ConvNoteJournalRetryBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {
    private LoggerUtility logger = new LoggerUtility('Conversation Note Journal Retry');
    private Boolean error = false;

    @InvocableMethod(
        label='Initiate Conversation Note Journal Retry Batch'
        description='Starts a process for posting journal entries to JOARK'
        category='Journal'
    )
    public static void initJournalBatcher() {
        Database.executeBatch(new CRM_ConvNoteJournalRetryBatch(), 40);
    }

    //################################################//
    //############ SELECTOR CLASS ####################//
    //################################################//

    private class JournalEntrySelector extends CRM_ApiSelector {
        public JournalEntrySelector() {
            super(false, false, false);
        }

        public List<Schema.SObjectField> getSObjectFieldList() {
            return new List<Schema.SObjectField>{
                Journal_Entry__c.Id,
                Journal_Entry__c.CRM_Conversation_Note__c,
                Journal_Entry__c.CRM_Created_By_Ident__c,
                Journal_Entry__c.CRM_Created_By_NAV_Unit__c,
                Journal_Entry__c.NAV_Case_Reference__c,
                Journal_Entry__c.CRM_Theme_Code__c,
                Journal_Entry__c.CRM_Subtheme_Code__c,
                Journal_Entry__c.Subtheme__c,
                Journal_Entry__c.Theme__c,
                Journal_Entry__c.CRM_NAV_Case_Legacy_System__c,
                Journal_Entry__c.CRM_Journal_Post_Type__c,
                Journal_Entry__c.Journal_Entry_Status__c,
                Journal_Entry__c.Journal_Entry_ID__c
            };
        }

        public Schema.SObjectType getSObjectType() {
            return Journal_Entry__c.sObjectType;
        }

        private String getJournalConditions() {
            return 'CRM_Conversation_Note__c != null AND Journal_Entry_Status__c = \'Failed\'';
        }

        public String getJournalEntriesToJournal() {
            fflib_QueryFactory query = newQueryFactory();
            query.setCondition(getJournalConditions());

            return query.toSOQL();
        }
    }

    //################################################//
    //###### BATCH IMPLEMENTATION CLASS ##############//
    //################################################//

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(new JournalEntrySelector().getJournalEntriesToJournal());
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Conversation_Note__c> convNotesToUpdate = new List<Conversation_Note__c>();
        List<Journal_Entry__c> jEntriesToUpdate = new List<Journal_Entry__c>();
        Set<Id> processedConvNoteIds = new Set<Id>();

        for (Journal_Entry__c jEntry : (List<Journal_Entry__c>) scope) {
            jEntry.NAV_Case_Reference__c = jEntry.NAV_Case_Reference__c; //Self initialization for flow null handling
            jEntry.CRM_NAV_Case_Legacy_System__c = jEntry.CRM_NAV_Case_Legacy_System__c; //Self initialization for flow null handling
            Map<String, Object> flowInputs = new Map<String, Object>{
                'Journal_Entry_SF' => jEntry,
                'PERFORM_DML' => false
            };

            Flow.Interview journalFlow = Flow.Interview.createInterview('Journal_Conversation_Note_Retry', flowInputs);
            journalFlow.start();
            jEntriesToUpdate.add((Journal_Entry__c) journalFlow.getVariableValue('Journal_Entry_SF'));
            if (processedConvNoteIds.contains(jEntry.CRM_Conversation_Note__c))
                continue; //Already added to list for update
            convNotesToUpdate.add((Conversation_Note__c) journalFlow.getVariableValue('Conversation_Note_Record'));
            processedConvNoteIds.add(jEntry.CRM_Conversation_Note__c);
        }

        List<Database.SaveResult> jEntryUpdRes = Database.update(jEntriesToUpdate, false);
        List<Database.SaveResult> convNoteUpdRes = Database.update(convNotesToUpdate, false);

        verifyUpdateResults(jEntryUpdRes);
        verifyUpdateResults(convNoteUpdRes);
        logger.publish();
    }

    private void verifyUpdateResults(List<Database.SaveResult> updResults) {
        for (Database.SaveResult updRes : updResults) {
            if (updRes.isSuccess()) {
                //Successfull update
            } else {
                String errorMsg = 'Failed to update record with id: ' + updRes.getId() + '\n';
                for (Database.Error err : updRes.getErrors()) {
                    errorMsg += err.getMessage() + '\n';
                }
                this.error = true;
                logger.error(errorMsg, null, CRM_ApplicationDomain.Domain.NKS);
            }
        }
    }

    //If error occurred a critical log entry is logged that will publish automatically to slack
    public void finish(Database.BatchableContext BC) {
        if (this.error) {
            logger.critical('One of more records failed to update', null, CRM_ApplicationDomain.Domain.NKS); //Log a critical entry that should be published to slack for follow up;
            logger.publish();
        }
    }
}