force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Journal_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Journal_Status__c</fullName>
    <description>Depicts the journal status of the conversation note. By default no journal entry is created.</description>
    <label>Journal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Journaled</fullName>
                <default>true</default>
                <label>Not Journaled</label>
            </value>
            <value>
                <fullName>Journal Error</fullName>
            </value>
            <value>
                <fullName>Journal Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Object used to reflect a journal entry that has been sent to JOARK.</description>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{0000}</displayFormat>
        <label>Journal Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/objects/Journal_Entry__c/fields/CRM_Conversation_Note__c.field-meta.xml
<CustomField>
    <fullName>CRM_Conversation_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a conversation note if the journal entry is related to this.</description>
    <label>Conversation Note</label>
    <referenceTo>Conversation_Note__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_NAV_Case_Legacy_System__c.field-meta.xml
<CustomField>
    <fullName>CRM_NAV_Case_Legacy_System__c</fullName>
    <description>If case type = FAGSAK, this defines which legacy system that handles the case. Required for journal purposes using Dokarkiv API</description>
    <label>NAV Case Legacy System</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/core-functionality/classes/CRM_ConvNoteJournalHelper_Test.cls
@isTest
public class CRM_ConvNoteJournalHelper_Test {
    @TestSetup
    static void makeData() {
        CRM_HENV_TestDataFactory.createRecord(new Common_Code__c(CRM_Code_Set__c = 'Tema', CRM_Code__c = 'DAG'));
        CRM_HENV_TestDataFactory.createRecord(new Conversation_Note__c(CRM_Conversation_Note__c = 'DUMMY TEXT'));
    }

    @isTest
    static void testAsyncJournal() {
        ApiMock.setTestMock('POST_CREATE_JOURNAL', 200, 'OK');
        Conversation_Note__c convNote = [SELECT Id, CRM_API_Reference__c FROM Conversation_Note__c LIMIT 1];
        CRM_ConvNoteJournalHelper.JournalRequest jRequest = new CRM_ConvNoteJournalHelper.JournalRequest();
        List<CRM_ConvNoteJournalHelper.JournalRequest> requestList = new List<CRM_ConvNoteJournalHelper.JournalRequest>();

        jRequest.Journal_Case_ID = '123TESTABC';
        jRequest.Journal_Case_Legacy_System = 'A01';
        jRequest.Journal_Entry_NAV_Ident = 'Z999999';
        jRequest.Journal_Entry_Unit = '4100';
        jRequest.Journal_Theme_Code = 'DAG';
        jRequest.recordId = convNote.Id;

        requestList.add(jRequest);

        Test.startTest();
        CRM_ConvNoteJournalHelper.handleRequest(requestList);
        Test.stopTest();

        Conversation_Note__c updatedConvNote = [
            SELECT Id, CRM_Journal_Status__c
            FROM Conversation_Note__c
            WHERE Id = :convNote.Id
        ];
        System.assert(updatedConvNote.CRM_Journal_Status__c.equalsIgnoreCase('Journal Completed'));
        System.assertEquals(1, [SELECT COUNT() FROM Journal_Entry__c WHERE CRM_NAV_Case_Legacy_System__c = 'A01']);
    }
}