force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Theme__c.field-meta.xml
<CustomField>
    <fullName>CRM_Theme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to common code theme.</description>
    <label>Theme</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Common_Code__c.CRM_Code_Set__c</field>
            <operation>equals</operation>
            <value>Tema</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Common_Code__c</referenceTo>
    <relationshipLabel>Conversation Notes</relationshipLabel>
    <relationshipName>CRM_Conversation_Notes_Theme</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_Henvendelse_BehandlingsId__c.field-meta.xml
<CustomField>
    <fullName>CRM_Henvendelse_BehandlingsId__c</fullName>
    <externalId>true</externalId>
    <label>Henvendelse BehandlingsId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>CRM_Message_Text__c</fullName>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Sent_date__c.field-meta.xml
<CustomField>
    <fullName>CRM_Sent_date__c</fullName>
    <label>Sent date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_Theme__c.field-meta.xml
<CustomField>
    <fullName>CRM_Theme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to common code theme.</description>
    <label>Theme</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Common_Code__c.CRM_Code_Set__c</field>
            <operation>equals</operation>
            <value>Tema</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Common_Code__c</referenceTo>
    <relationshipLabel>Threads</relationshipLabel>
    <relationshipName>CRM_Threads_Theme</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_Thread_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread_Type__c</fullName>
    <label>Thread Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEFAULT</fullName>
                <default>true</default>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>STB</fullName>
            </value>
            <value>
                <fullName>AAREG_EXP</fullName>
            </value>
            <value>
                <fullName>AAREG_INT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ArchiveRerunner.cls
public with sharing class ArchiveRerunner {
    // Input: Static resource in JSON format with ID of records to rerun
    public static void rerunFailedArchivation(String staticResourceName, String namespace) {
        StaticResource sr;
        if (!Test.isRunningTest()) {
            sr = [SELECT Body FROM StaticResource WHERE Name = :staticResourceName LIMIT 1];
        }

        String body = Test.isRunningTest()
            ? '[{ "attributes": { "type": "Thread__c", "url": "/services/data/v56.0/sobjects/Thread__c/a0W1l0000039XlPEAU"}, "Id": "a0W1l0000039XlPEAU"}]'
            : sr.Body.toString();
        if (body == null) {
            System.debug('Error: No body found!');
            return;
        }

        List<RecordsToArchive> recordsToArchive = (List<RecordsToArchive>) JSON.deserialize(
            body,
            List<RecordsToArchive>.class
        );
        List<Id> recordIds = new List<Id>();
        for (RecordsToArchive record : recordsToArchive) {
            recordIds.add(record.Id);
        }
        if (recordIds.isEmpty()) {
            System.debug('Error: No record ids found!');
            return;
        }
        System.debug('recordIds: ' + recordIds);
        ArchiveRerunBatch ab = new ArchiveRerunBatch(recordIds, namespace);
    }

    // For manual ArchiveRerunBatch
    public static void postToArchive(List<ArchivePostWrapper> inputs) {
        LoggerUtility logger = new LoggerUtility('Arkiv');
        List<Id> threadList = new List<Id>();

        for (ArchivePostWrapper input : inputs) {
            if (input.archiveObject.getSObjectType().getDescribe().getName() == 'Thread__c') {
                threadList.add(input.archiveObject.Id);
            }
        }
        Map<Id, Thread__c> threadMap = null;
        try {
            threadMap = new Map<Id, Thread__c>(
                [
                    SELECT
                        Id,
                        (
                            SELECT
                                Id,
                                Name,
                                CRM_Message_Text__c,
                                CRM_Thread_Type__c,
                                CRM_Read_Datetime__c,
                                CRM_Sent_date__c,
                                CRM_Henvendelse_BehandlingsId__c
                            FROM Messages__r
                        )
                    FROM Thread__c
                    WHERE Id IN :threadList
                ]
            );
        } catch (Exception e) {
            logger.error('Feil med henting av tråder for arkivering: ' + e, null);
        }

        List<ArchiveRequestWrapper> archiveObjects = new List<ArchiveRequestWrapper>();
        for (ArchivePostWrapper input : inputs) {
            SObject archiveObject = input.archiveObject;
            if (input.archiveObject.getSObjectType().getDescribe().getName() == 'Thread__c') {
                archiveObject = (SObject) threadMap?.get(input.archiveObject.Id);
            }
            archiveObjects.add(
                new ArchiveRequestWrapper(
                    input.opprettetAv,
                    input.aktoerid,
                    input.fnr,
                    input.tema,
                    input.konfidentiellt,
                    archiveObject
                )
            );
        }

        List<ArchiveService.ArchiveResponseWrapper> response = new ArchiveService().postToArchive(archiveObjects);
        if (response == null) {
            logger.error('Feil med arkivering, response == null', null);
        }
        for (ArchiveService.ArchiveResponseWrapper archiveResponse : response) {
            if (response[0].id == null) {
                logger.error('Feil med arkivering, response.Id == null', null);
            }
        }
        logger.publish();
    }

    // WRAPPERS //

    public class RecordsToArchive {
        public String id;
    }

    public class ArchivePostWrapper {
        public SObject archiveObject;
        public String opprettetAv;
        public String aktoerid;
        public String fnr;
        public String tema;
        public Boolean konfidentiellt;

        // For manual ArchiveRerunBatch
        public ArchivePostWrapper(SObject archiveObject, String opprettetAv) {
            this.archiveObject = archiveObject;
            this.opprettetAv = opprettetAv;
            switch on archiveObject.getSObjectType().getDescribe().getName() {
                when 'Thread__c' {
                    this.fnr = ((Thread__c) archiveObject)?.CRM_Account__r?.CRM_Person__r?.Name;
                    this.aktoerid = ((Thread__c) archiveObject)?.CRM_Account__r?.CRM_Person__r?.INT_ActorId__c;
                    this.konfidentiellt = ((Thread__c) archiveObject)?.STO_Sensitive_Information__c;
                    this.tema = ((Thread__c) archiveObject).CRM_Theme__c;
                }
                when 'Conversation_note__c' {
                    this.konfidentiellt = true;
                    this.aktoerid = ((Conversation_Note__c) archiveObject)
                        ?.CRM_Account__r
                        ?.CRM_Person__r
                        ?.INT_ActorId__c;
                    this.fnr = ((Conversation_Note__c) archiveObject)?.CRM_Account__r?.CRM_Person__r?.Name;
                    this.tema = ((Conversation_Note__c) archiveObject).CRM_Theme__c;
                }
            }
        }
    }
}