force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_Henvendelse_BehandlingsId__c.field-meta.xml
<CustomField>
    <fullName>CRM_Henvendelse_BehandlingsId__c</fullName>
    <externalId>true</externalId>
    <label>Henvendelse BehandlingsId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ArchiveRerunnerTest.cls
@isTest
private class ArchiveRerunnerTest {
    // TODO: Upload actual static resource for testing so it works
    @TestSetup
    static void makeData() {
        CRM_HENV_TestDataFactory.createRecord(new Conversation_Note__c());
        CRM_HENV_TestDataFactory.createRecord(new Message__c());
        CRM_HENV_TestDataFactory.createRecord(new Thread__c(CRM_Henvendelse_BehandlingsId__c = '123TEST'));
    }

    @isTest
    static void testRerunFailedArchivation() {
        Test.startTest();
        ArchiveRerunner.rerunFailedArchivation('ArchiveRerunnerTestResource');
        Test.stopTest();

        // TODO: Assert something
    }

}