force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_API_Reference__c.field-meta.xml
<CustomField>
    <fullName>CRM_API_Reference__c</fullName>
    <description>Record reference that is exposed via API</description>
    <externalId>true</externalId>
    <label>API Reference</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Henvendelse_BehandlingsId__c.field-meta.xml
<CustomField>
    <fullName>CRM_Henvendelse_BehandlingsId__c</fullName>
    <externalId>true</externalId>
    <label>Henvendelse BehandlingsId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/classes/CRM_ApiReferenceBatcher_Test.cls
@isTest
public class CRM_ApiReferenceBatcher_Test {
    @TestSetup
    static void makeData() {
        CRM_HENV_TestDataFactory.createRecord(new Conversation_Note__c());
        CRM_HENV_TestDataFactory.createRecord(new Message__c());
        CRM_HENV_TestDataFactory.createRecord(new Thread__c(CRM_Henvendelse_BehandlingsId__c = '123TEST'));
    }

    @isTest
    static void testBatchReferenceGeneration() {
        String query = 'SELECT Id, CRM_API_Reference__c FROM Conversation_Note__c';
        CRM_ApiReferenceBatcher batcher = new CRM_ApiReferenceBatcher(query);
        String initialRef = [SELECT Id, CRM_API_Reference__c FROM Conversation_Note__c LIMIT 1]?.CRM_API_Reference__c;

        Test.startTest();
        Database.executeBatch(batcher);
        Test.stopTest();

        System.assertNotEquals(
            initialRef,
            [SELECT Id, CRM_API_Reference__c FROM Conversation_Note__c LIMIT 1]
            ?.CRM_API_Reference__c
        );
        System.assertNotEquals(
            null,
            [SELECT Id, CRM_API_Reference__c FROM Conversation_Note__c LIMIT 1]
            ?.CRM_API_Reference__c
        );
    }

    @isTest
    static void testThreadRefSwitch() {
        String query = 'SELECT Id, CRM_API_Reference__c, CRM_Henvendelse_BehandlingsId__c FROM Thread__c';
        CRM_ApiReferenceBatcher batcher = new CRM_ApiReferenceBatcher(true, query);

        Test.startTest();
        Database.executeBatch(batcher);
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM Thread__c WHERE CRM_API_Reference__c = '123TEST']);
    }
}