force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Journal_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Journal_Status__c</fullName>
    <description>Depicts the journal status of the conversation note. By default no journal entry is created.</description>
    <label>Journal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Journaled</fullName>
                <default>true</default>
                <label>Not Journaled</label>
            </value>
            <value>
                <fullName>Journal Error</fullName>
            </value>
            <value>
                <fullName>Journal Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Theme__c.field-meta.xml
<CustomField>
    <fullName>CRM_Theme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to common code theme.</description>
    <label>Theme</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Common_Code__c.CRM_Code_Set__c</field>
            <operation>equals</operation>
            <value>Tema</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Common_Code__c</referenceTo>
    <relationshipLabel>Conversation Notes</relationshipLabel>
    <relationshipName>CRM_Conversation_Notes_Theme</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_Henvendelse_BehandlingsId__c.field-meta.xml
<CustomField>
    <fullName>CRM_Henvendelse_BehandlingsId__c</fullName>
    <externalId>true</externalId>
    <label>Henvendelse BehandlingsId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>CRM_Message_Text__c</fullName>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Sent_date__c.field-meta.xml
<CustomField>
    <fullName>CRM_Sent_date__c</fullName>
    <label>Sent date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_Theme__c.field-meta.xml
<CustomField>
    <fullName>CRM_Theme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to common code theme.</description>
    <label>Theme</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Common_Code__c.CRM_Code_Set__c</field>
            <operation>equals</operation>
            <value>Tema</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Common_Code__c</referenceTo>
    <relationshipLabel>Threads</relationshipLabel>
    <relationshipName>CRM_Threads_Theme</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_Thread_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread_Type__c</fullName>
    <label>Thread Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEFAULT</fullName>
                <default>true</default>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>STB</fullName>
            </value>
            <value>
                <fullName>AAREG_EXP</fullName>
            </value>
            <value>
                <fullName>AAREG_INT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ArchiveRerunBatch.cls
public with sharing class ArchiveRerunBatch implements Database.Batchable<Id>, Database.AllowsCallouts {
    private List<Id> idsToArchive;
    private string opprettetAv;

    public ArchiveRerunBatch(List<Id> idsToArchive, String opprettetAv) {
        this.idsToArchive = idsToArchive;
        this.opprettetAv = opprettetAv;
        Database.executeBatch(this);
    }

    public Iterable<Id> start(Database.BatchableContext BC) {
        return idsToArchive;
    }

    public void execute(Database.BatchableContext BC, List<Id> scope) {
        String objName = scope[0].getSObjectType().getDescribe().getName();
        List<SObject> records = new List<SObject>();
        if (objName == 'Thread__c') {
            records = [
                SELECT
                    Id,
                    CRM_Account__r.CRM_Person__r.Name,
                    CRM_Account__r.CRM_Person__r.INT_ActorId__c,
                    STO_Sensitive_Information__c,
                    CRM_Theme__c,
                    (
                        SELECT
                            Id,
                            Name,
                            CRM_Message_Text__c,
                            CRM_Thread_Type__c,
                            CRM_Read_Datetime__c,
                            CRM_Sent_date__c,
                            CRM_Henvendelse_BehandlingsId__c
                        FROM Messages__r
                    )
                FROM Thread__c
                WHERE
                    CRM_Thread_Type__c IN ('STO', 'STB', 'BTO')
                    AND CRM_Journal_Status__c = 'Not Journaled'
                    AND Id IN :scope
            ];
        } else if (objName == 'Conversation_Note__c') {
            records = [
                SELECT
                    Id,
                    CRM_Account__r.CRM_Person__r.INT_ActorId__c,
                    CRM_Account__r.CRM_Person__r.Name,
                    CRM_Theme__c,
                    CRM_Conversation_Note__c
                FROM Conversation_Note__c
                WHERE CRM_Journal_Status__c = 'Not Journaled' AND Id IN :scope
            ];
        }

        List<ArchiveRerunner.ArchivePostWrapper> postList = new List<ArchiveRerunner.ArchivePostWrapper>();
        for (SObject rec : records) {
            postList.add(new ArchiveRerunner.ArchivePostWrapper(rec, opprettetAv));
        }
        System.debug('postList: ' + postList);
        ArchiveRerunner.postToArchive(postList);
    }

    public void finish(Database.BatchableContext BC) {
    }
}