force-app/main/default/core-functionality/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Conversation_Note__c/fields/CRM_Journal_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Journal_Status__c</fullName>
    <description>Depicts the journal status of the conversation note. By default no journal entry is created.</description>
    <label>Journal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Journaled</fullName>
                <default>true</default>
                <label>Not Journaled</label>
            </value>
            <value>
                <fullName>Journal Error</fullName>
            </value>
            <value>
                <fullName>Journal Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/classes/ArchiveBatch.cls
/**
 * @description       :
 * @author            : mamikals
 * @group             :
 * @last modified on  : 21-02-2023
 * @last modified by  : mamikals
 **/
public with sharing class ArchiveBatch implements Database.Batchable<sObject> {
    public ArchiveBatch(Date startDate, Date endDate, String archiveObject) {
        this.startDate = startDate;
        this.endDate = endDate;
        if (archiveObject == 'thread__c') {
            query = 'Select Id from Thread__c where STO_Sensitive_Information_Date__c  <= :endDate OR (CRM_Journal_Status__c=\'Not Journaled\' AND (CRM_Closed_Date__c <= :endDate and CRM_Closed_Date__c  >= :startDate))';
        } else if (archiveObject == 'conversation_note__c') {
            query = 'Select Id from Conversation_note__c where STO_Sensitive_Information_Date__c  <= :endDate and STO_Sensitive_Information_Date__c  >= :startDate';
        }
    }
    private final Date startDate;
    private final Date endDate;
    private final String query;

    public Database.QueryLocator start(Database.BatchableContext BC) {
        if (query == null)
            return null;
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        LoggerUtility logger = new LoggerUtility();
        for (sObject nice : scope) {
            logger.info(nice.Id, null);
        }
        logger.publish();
    }

    public void finish(Database.BatchableContext BC) {
    }
}