force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Object used to reflect a journal entry that has been sent to JOARK.</description>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{0000}</displayFormat>
        <label>Journal Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Created_By_Ident__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_Ident__c</fullName>
    <description>NAV ident of the user who created the journal entry.</description>
    <externalId>true</externalId>
    <label>Created By Ident</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Journal_Date__c.field-meta.xml
<CustomField>
    <fullName>CRM_Journal_Date__c</fullName>
    <description>States the moment in time the journal entry was submitted to the archive.</description>
    <label>Journal Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Theme_Code__c.field-meta.xml
<CustomField>
    <fullName>CRM_Theme_Code__c</fullName>
    <description>The unique code from common codes</description>
    <formula>Theme__r.CRM_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Theme Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Journal_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Journal_Entry_ID__c</fullName>
    <description>Unique identifier to a JOARK journal post.</description>
    <externalId>true</externalId>
    <label>Journal Entry ID</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RestServices/API-wrappers/CRM_JournalfortInformasjon.cls
global class CRM_JournalfortInformasjon {
    global String journalforerNavIdent;
    global String journalfortDato;
    global String journalfortTema;
    global String journalpostId;

    global CRM_JournalfortInformasjon(Journal_Entry__c jEntry) {
        this.journalpostId = jEntry.Journal_Entry_ID__c;
        this.journalfortDato = jEntry.CRM_Journal_Date__c != null
            ? jEntry.CRM_Journal_Date__c.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ')
            : null;
        this.journalfortTema = jEntry.CRM_Theme_Code__c;
        this.journalforerNavIdent = jEntry.CRM_Created_By_Ident__c;
    }
}