force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Object used to reflect a journal entry that has been sent to JOARK.</description>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{0000}</displayFormat>
        <label>Journal Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Created_By_Ident__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_Ident__c</fullName>
    <description>NAV ident of the user who created the journal entry.</description>
    <externalId>true</externalId>
    <label>Created By Ident</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Journal_Date__c.field-meta.xml
<CustomField>
    <fullName>CRM_Journal_Date__c</fullName>
    <description>States the moment in time the journal entry was submitted to the archive.</description>
    <label>Journal Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a thread if the journal entry is related to this.</description>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Journal_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Journal_Entry_ID__c</fullName>
    <description>Unique identifier to a JOARK journal post.</description>
    <externalId>true</externalId>
    <label>Journal Entry ID</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/NAV_Case_Reference__c.field-meta.xml
<CustomField>
    <fullName>NAV_Case_Reference__c</fullName>
    <description>Unique reference to a NAV case in a legacy system</description>
    <label>NAV Case Reference</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to common code for the theme the journal entry was given.</description>
    <label>Theme</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Common_Code__c.CRM_Code_Set__c</field>
            <operation>equals</operation>
            <value>Tema</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Common_Code__c</referenceTo>
    <relationshipLabel>Journal Entries (Theme)</relationshipLabel>
    <relationshipName>Journal_Entries_Theme</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/objects/Message__c/fields/CRM_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Event_Type__c</fullName>
    <description>If message is an event, this field describe the type of event</description>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CRM_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>END_OF_CHAT</fullName>
            </value>
            <value>
                <fullName>UNIT_TRANSFER</fullName>
            </value>
            <value>
                <fullName>QUEUE_TRANSFER</fullName>
            </value>
            <value>
                <fullName>JOURNAL</fullName>
            </value>
            <value>
                <fullName>INTERNAL_MESSAGE</fullName>
            </value>
            <value>
                <fullName>EXTERNAL_MESSAGE</fullName>
            </value>
            <value>
                <fullName>REDACTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_External_Message__c.field-meta.xml
<CustomField>
    <fullName>CRM_External_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_Contact__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_First_Name__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_First_Name__c</fullName>
    <description></description>
    <formula>
    IF( CRM_From_Contact__c != null,
		CRM_From_Contact__r.FirstName,
        IF(CRM_From_User__c != null,
		    CRM_From_User__r.FirstName,
            CRM_From_Ident__c 
        )
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>From First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_Label__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_Label__c</fullName>
    <label>From Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_User__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>CRM_Message_Text__c</fullName>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Read__c.field-meta.xml
<CustomField>
    <fullName>CRM_Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Sent_date__c.field-meta.xml
<CustomField>
    <fullName>CRM_Sent_date__c</fullName>
    <label>Sent date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Message</fullName>
                <default>true</default>
                <label>Message</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_Created_By_Ident__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_Ident__c</fullName>
    <description>NAV ident of the user creating the thread.</description>
    <externalId>true</externalId>
    <label>Created By</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_isActive__c.field-meta.xml
<CustomField>
    <fullName>CRM_isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_Number_of_External_Messages__c.field-meta.xml
<CustomField>
    <fullName>CRM_Number_of_External_Messages__c</fullName>
    <label>Number of External Messages</label>
    <summaryFilterItems>
        <field>Message__c.CRM_External_Message__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Message__c.CRM_Thread__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_Related_Object__c.field-meta.xml
<CustomField>
    <fullName>CRM_Related_Object__c</fullName>
    <label>Related Object</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_MessageHelper.cls
/**
 * Helper class for the Messaging solution
 * @Author Lars Petter Johnsen
 * @Date 20.05.2021
 */
public with sharing class CRM_MessageHelper {
    @AuraEnabled(cacheable=true)
    public static String getRecordObjectType(Id recordId) {
        String objectType = recordId.getSObjectType().getDescribe().getName();
        return objectType;
    }

    @AuraEnabled
    public static string getUserContactId() {
        return [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()]?.ContactId;
    }

    @AuraEnabled(cacheable=true)
    public static List<Thread__c> getThreadsCollection(Id recordId, Boolean singleThread) {
        if (singleThread == false) {
            return getThreads(recordId);
        } else {
            List<Thread__c> tList = new List<Thread__c>();
            tList.add(getSingleThread(recordId));
            return tList;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Journal_Entry__c> getJournalEntries(Id threadId) {
        return [
            SELECT
                Id,
                Theme__c,
                NAV_Case_Reference__c,
                CRM_Journal_Date__c,
                Journal_Entry_ID__c,
                CRM_Created_By_Ident__c
            FROM Journal_Entry__c
            WHERE CRM_Thread__c = :threadId
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Thread__c> getThreads(Id recordId) {
        List<Thread__c> threadList;
        try {
            threadList = [
                SELECT Id, CRM_Number_of_External_Messages__c, CRM_Related_Object__c, CRM_isActive__c
                FROM Thread__c
                WHERE CRM_Related_Object__c = :recordId
            ];
        } catch (Exception e) {
        }
        return threadList;
    }
    @AuraEnabled(cacheable=true)
    public static Thread__c getSingleThread(Id recordId) {
        try {
            if (recordId.getSobjectType() == Thread__c.sObjectType) {
                return getThreadFromThreadId(recordId);
            }
            Thread__c t = [
                SELECT Id, CRM_Number_of_External_Messages__c, CRM_Related_Object__c, CRM_isActive__c
                FROM Thread__c
                WHERE CRM_Related_Object__c = :recordId
                LIMIT 1
            ];

            return t;
        } catch (Exception e) {
            return null;
        }
    }

    @AuraEnabled(cacheable=true)
    public static Thread__c getThreadFromThreadId(Id recordId) {
        try {
            Thread__c t = [
                SELECT Id, CRM_Number_of_External_Messages__c, CRM_Related_Object__c, CRM_isActive__c
                FROM Thread__c
                WHERE Id = :recordId
                LIMIT 1
            ];

            return t;
        } catch (Exception e) {
            return null;
        }
    }

    @AuraEnabled
    public static void createThread(Id recordId) {
        Thread__c newThread = new Thread__c();
        newThread.CRM_Related_Object__c = recordId;
        insert newThread;
    }

    @AuraEnabled(cacheable=true)
    public static List<Message__c> getMessagesFromThread(Id threadId) {
        try {
            List<Message__c> msgList = new List<Message__c>();
            String query =
                'SELECT Id, CRM_Message_Text__c, CRM_Type__c, CRM_Event_Type__c, crm_sent_date__c, CRM_From_User__c, CRM_From_Contact__c, CRM_From_First_Name__c, CRM_External_Message__c, CRM_From_Label__c FROM Message__c WHERE ' +
                getThreadQuery(threadId) +
                ' ORDER BY CRM_Sent_date__c ASC';
            for (Message__c m : Database.query(query)) {
                if (m.CRM_Message_Text__c != null) {
                    msgList.add(m);
                }
            }
            return msgList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static string getUserLisenceType(Id userId) {
        try {
            String userLicenseType = [SELECT UserType FROM User WHERE Id = :userId LIMIT 1].UserType;
            return userLicenseType;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    /**
     * Method for marking unread messages - called onload fromt the end user perspective. Does only represent customer read.
     * @Lars Petter Johnsen
     * @Date 31052021
     */
    @AuraEnabled
    public static void markAsRead(Id threadId) {
        String query = 'SELECT Id FROM Message__c WHERE CRM_Read__c = FALSE AND ' + getThreadQuery(threadId);
        List<Message__c> msgList = Database.query(query);
        for (Message__c msg : msgList) {
            msg.CRM_Read__c = true;
            msg.CRM_Read_Datetime__c = DateTime.now();
        }
        update msgList;
    }

    @AuraEnabled(cacheable=true)
    public static Id getThreadId(Id recordId) {
        return (recordId.getSobjectType() == Thread__c.sObjectType
            ? recordId
            : [SELECT Id FROM Thread__c WHERE CRM_Related_Object__c = :recordId LIMIT 1].Id);
    }

    /**
     * Creates a message
     * Used in the community components
     * @Author Lars Petter Johnsen
     */
    @AuraEnabled
    public static Boolean createMessage(Id threadId, String messageText, Id fromContactId) {
        Message__c m = new Message__c();
        m.CRM_Message_Text__c = messageText;
        m.CRM_Thread__c = threadId;
        m.CRM_From_Contact__c = fromContactId;
        m.CRM_Read__c = true;
        m.CRM_Read_Datetime__c = DateTime.now();

        Thread__c t = [SELECT Id, CRM_isActive__c FROM Thread__c WHERE Id = :threadId LIMIT 1][0];
        if (!t.CRM_isActive__c) {
            return false;
        }

        try {
            insert m;
            return true;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static String getThreadQuery(Id threadId) {
        if (threadId.getSobjectType() == Thread__c.sObjectType) {
            return 'CRM_Thread__c = :threadId';
        } else {
            return 'CRM_Thread__r.CRM_Related_Object__c = :threadId';
        }
    }
}