force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Object used to reflect a journal entry that has been sent to JOARK.</description>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{0000}</displayFormat>
        <label>Journal Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Created_By_Ident__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_Ident__c</fullName>
    <description>NAV ident of the user who created the journal entry.</description>
    <externalId>true</externalId>
    <label>Created By Ident</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Created_By_NAV_Unit__c.field-meta.xml
<CustomField>
    <fullName>CRM_Created_By_NAV_Unit__c</fullName>
    <description>NAV unit number of the user creating the journal entry.</description>
    <externalId>true</externalId>
    <label>Created By NAV Unit</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Journal_Date__c.field-meta.xml
<CustomField>
    <fullName>CRM_Journal_Date__c</fullName>
    <description>States the moment in time the journal entry was submitted to the archive.</description>
    <label>Journal Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_NAV_Case_Legacy_System__c.field-meta.xml
<CustomField>
    <fullName>CRM_NAV_Case_Legacy_System__c</fullName>
    <description>If case type = FAGSAK, this defines which legacy system that handles the case. Required for journal purposes using Dokarkiv API</description>
    <label>NAV Case Legacy System</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Subtheme_Code__c.field-meta.xml
<CustomField>
    <fullName>CRM_Subtheme_Code__c</fullName>
    <description>Unique subtheme code</description>
    <formula>Subtheme__r.CRM_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subtheme Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/CRM_Theme_Code__c.field-meta.xml
<CustomField>
    <fullName>CRM_Theme_Code__c</fullName>
    <description>The unique code from common codes</description>
    <formula>Theme__r.CRM_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Theme Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Journal_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Journal_Entry_ID__c</fullName>
    <description>Unique identifier to a JOARK journal post.</description>
    <externalId>true</externalId>
    <label>Journal Entry ID</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Journal_Entry_Status__c.field-meta.xml
<CustomField>
    <fullName>Journal_Entry_Status__c</fullName>
    <description>Status of the journal entry submission to JOARK</description>
    <label>Journal Entry Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/NAV_Case_Reference__c.field-meta.xml
<CustomField>
    <fullName>NAV_Case_Reference__c</fullName>
    <description>Unique reference to a NAV case in a legacy system</description>
    <label>NAV Case Reference</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/API/classes/RestServices/Selectors/CRM_JournalEntrySelector.cls
public inherited sharing class CRM_JournalEntrySelector extends CRM_ApiSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Journal_Entry__c.Id,
            Journal_Entry__c.CRM_Created_By_Ident__c,
            Journal_Entry__c.CRM_Created_By_NAV_Unit__c,
            Journal_Entry__c.CRM_Journal_Date__c,
            Journal_Entry__c.Journal_Entry_ID__c,
            Journal_Entry__c.Journal_Entry_Status__c,
            Journal_Entry__c.NAV_Case_Reference__c,
            Journal_Entry__c.CRM_Theme_Code__c,
            Journal_Entry__c.CRM_Subtheme_Code__c,
            Journal_Entry__c.CRM_NAV_Case_Legacy_System__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Journal_Entry__c.sObjectType;
    }

    public List<Journal_Entry__c> selectById(Set<Id> idSet) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id in :idSet');
        return (List<Journal_Entry__c>) Database.query(query.toSOQL());
    }
}