force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_Thread_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread_Type__c</fullName>
    <label>Thread Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEFAULT</fullName>
                <default>true</default>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>STB</fullName>
            </value>
            <value>
                <fullName>AAREG_EXP</fullName>
            </value>
            <value>
                <fullName>AAREG_INT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/fields/STO_Medskriv__c.field-meta.xml
<CustomField>
    <fullName>STO_Medskriv__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the user has allowed the thread to be used in medskriv</description>
    <label>Medskriv</label>
    <type>Checkbox</type>
</CustomField>

force-app/henvendelse-cache/classes/handlers/ThreadCacheHandlerTest.cls
@IsTest
public class ThreadCacheHandlerTest {
    @TestSetup
    private static void makeData() {
        User experienceCloudUser = (User) CRM_HENV_TestDataFactory.createExperienceCloudUser(); //New Person Account is also created
    }

    @IsTest
    static void shouldPublishEventWhenThreadCreatedByInternalUser() {
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        Test.startTest();
        CRM_HENV_TestDataFactory.createRecord(
            new Thread__c(
                CRM_Account__c = accountId,
                CRM_Thread_Type__c = 'CHAT'
            )
        );
        Test.stopTest();

        Assert.areEqual(
            1,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='INFO']
        );

        Assert.areEqual(
            0,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='ERROR']
        );
    }

    @IsTest
    static void shouldPublishEventWhenThreadIsCreatedByExperienceCloudUser() {
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        User experienceCloudUser = [
            SELECT Id
            FROM User
            WHERE AccountId = :accountId
        ];
        Test.startTest();
        System.runAs(experienceCloudUser) {
            Thread__c thread=new Thread__c(
                CRM_Account__c = accountId,
                CRM_Thread_Type__c = 'CHAT'
            );
            insert thread;
        }
        Test.stopTest();

        Assert.areEqual(
            1,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='INFO']
        );

        Assert.areEqual(
            0,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='ERROR']
        );
    }

    @IsTest
    static void shouldPublishEventWhenThreadIsUpdatedByInternalUser() {
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        Thread__c thread=(Thread__c) CRM_HENV_TestDataFactory.createRecord(
            new Thread__c(
                CRM_Account__c = accountId,
                CRM_Thread_Type__c = 'CHAT'
            )
        );

        Test.startTest();
        thread.STO_Medskriv__c=true;
        update thread;
        Test.stopTest();

        Assert.areEqual(
            2,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='INFO']
        );

        Assert.areEqual(
            0,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='ERROR']
        );
    }

    @IsTest
    static void shouldPublishEventWhenThreadIsUpdatedByExperienceCloudUser() {
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        User experienceCloudUser = [
            SELECT Id
            FROM User
            WHERE AccountId = :accountId
        ];
        
        Thread__c thread=(Thread__c) CRM_HENV_TestDataFactory.createRecord(
            new Thread__c(
                CRM_Account__c = accountId,
                CRM_Thread_Type__c = 'CHAT',
                OwnerId = experienceCloudUser.Id
            )
        );

        Test.startTest();
        System.runAs(experienceCloudUser) {
            thread.STO_Medskriv__c=true;
            update thread;
        }

        Test.stopTest();

        Assert.areEqual(
            2,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='INFO']
        );

        Assert.areEqual(
            0,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='ERROR']
        );
    }
}