force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_isActive__c.field-meta.xml
<CustomField>
    <fullName>CRM_isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/API/classes/RestServices/CRM_HenvThreadCloseRestService_Test.cls
@isTest
public class CRM_HenvThreadCloseRestService_Test {
    @TestSetup
    static void makeData() {
        CRM_HENV_TestDataFactory.createRecord(new Thread__c());
    }

    @isTest
    static void testThreadClose() {
        Thread__c thread = [SELECT Id, CRM_API_Reference__c FROM Thread__c LIMIT 1];

        RestRequest req = new RestRequest();
        RestResponse resp = new RestResponse();

        req.requestURI =
            Url.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/henvendelse/meldingskjede/lukk';
        req.addParameter('kjedeId', thread.CRM_API_Reference__c);
        req.httpMethod = 'POST';
        req.headers.put('X-Correlation-ID', '123TEST');
        req.headers.put('X-ACTING-NAV-IDENT', 'Z999999');
        RestContext.request = req;
        RestContext.response = resp;

        Test.startTest();
        CRM_HenvThreadCloseRestService.closeThread();
        Test.stopTest();

        thread = [SELECT Id, CRM_isActive__c, CRM_Last_Edited_By__c FROM Thread__c WHERE ID = :thread.Id];
        System.assertEquals(204, RestContext.response.statusCode);
        System.assertEquals(thread.CRM_Last_Edited_By__c, 'Z999999');
    }

    @isTest
    static void testDmlException() {
        Thread__c thread = [SELECT Id, CRM_API_Reference__c FROM Thread__c LIMIT 1];

        RestRequest req = new RestRequest();
        RestResponse resp = new RestResponse();

        req.requestURI =
            Url.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/henvendelse/meldingskjede/lukk';
        req.addParameter('kjedeId', thread.CRM_API_Reference__c);
        req.httpMethod = 'POST';
        req.headers.put('X-Correlation-ID', '123TEST');
        req.headers.put('X-ACTING-NAV-IDENT', 'Z999999');
        RestContext.request = req;
        RestContext.response = resp;

        Test.startTest();
        CRM_HenvThreadCloseRestService.simulateException(new DmlException('Something failed'));
        CRM_HenvThreadCloseRestService.closeThread();
        Test.stopTest();

        System.assertEquals(500, RestContext.response.statusCode);
    }

    @isTest
    static void testGenericExceoption() {
        Thread__c thread = [SELECT Id, CRM_API_Reference__c FROM Thread__c LIMIT 1];

        RestRequest req = new RestRequest();
        RestResponse resp = new RestResponse();

        req.requestURI =
            Url.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/henvendelse/meldingskjede/lukk';
        req.addParameter('kjedeId', thread.CRM_API_Reference__c);
        req.httpMethod = 'POST';
        req.headers.put('X-Correlation-ID', '123TEST');
        req.headers.put('X-ACTING-NAV-IDENT', 'Z999999');
        RestContext.request = req;
        RestContext.response = resp;

        Test.startTest();
        CRM_HenvThreadCloseRestService.simulateException(new StringException('Something failed'));
        CRM_HenvThreadCloseRestService.closeThread();
        Test.stopTest();

        System.assertEquals(500, RestContext.response.statusCode);
    }
}