force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_Henvendelse_BehandlingsId__c.field-meta.xml
<CustomField>
    <fullName>CRM_Henvendelse_BehandlingsId__c</fullName>
    <externalId>true</externalId>
    <label>Henvendelse BehandlingsId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>CRM_Message_Text__c</fullName>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Sent_date__c.field-meta.xml
<CustomField>
    <fullName>CRM_Sent_date__c</fullName>
    <label>Sent date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_Thread_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread_Type__c</fullName>
    <label>Thread Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEFAULT</fullName>
                <default>true</default>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>STB</fullName>
            </value>
            <value>
                <fullName>AAREG_EXP</fullName>
            </value>
            <value>
                <fullName>AAREG_INT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/core-functionality/classes/ArchiveHandler.cls
/**
 * @description       :
 * @author            : mamikals
 * @group             :
 * @last modified on  : 28-02-2023
 * @last modified by  : mamikals
 **/
public inherited sharing class ArchiveHandler {
    public static String checkNull(String value) {
        return String.isBlank(value) ? '' : value;
    }

    @InvocableMethod(
        label='Post data to archive server'
        description='Sends all the data of a query to the archive server.'
    )
    public static List<String> postToArchive(List<ArchivePostWrapper> inputs) {
        List<ArchiveRequestWrapper> archiveObjects = new List<ArchiveRequestWrapper>();
        ArchiveService service = new ArchiveService();
        for (ArchivePostWrapper input : inputs) {
            SObject archiveObject = input.archiveObject;
            if (input.archiveObject.getSObjectType().getDescribe().getName() == 'Thread__c') {
                try {
                    List<Thread__c> threadWithMessage = [
                        SELECT
                            Id,
                            (
                                SELECT
                                    Id,
                                    Name,
                                    CRM_Message_Text__c,
                                    CRM_Thread_Type__c,
                                    CRM_Read_Datetime__c,
                                    CRM_Sent_date__c,
                                    CRM_Henvendelse_BehandlingsId__c
                                FROM Messages__r
                            )
                        FROM Thread__c
                        WHERE Id = :input.archiveObject.Id
                    ];
                    archiveObject = (SObject) threadWithMessage[0];
                } catch (Exception e) {
                    LoggerUtility logger = new LoggerUtility('Arkiv');
                    logger.error(
                        'Feil med å hente tråd ' +
                        input.archiveObject.Id +
                        ' for arkivering: ' +
                        e,
                        input.archiveObject
                    );
                }
            }
            input.aktoerid = checkNull(input.aktoerid);
            input.fnr = checkNull(input.fnr);
            input.orgnr = checkNull(input.orgnr);
            input.tema = checkNull(input.tema);
            input.dokumentasjonId = checkNull(input.dokumentasjonId);

            ArchiveRequestWrapper inputWrapper = new ArchiveRequestWrapper(
                input.opprettetAv,
                input.aktoerid,
                input.fnr,
                input.orgnr,
                input.tema,
                input.konfidentiellt,
                input.dokumentasjonId,
                input.archiveObject
            );
            archiveObjects.add(inputWrapper);
        }
        List<ArchiveResponseWrapper> resp = service.postToArchive(archiveObjects);
        List<String> returnStrings = new List<String>();
        for (ArchiveResponseWrapper archive : resp) {
            returnStrings.add(archive.dokumentasjonId);
        }
        return returnStrings;
    }

    public class ArchivePostWrapper {
        @invocableVariable(required=true)
        public Sobject archiveObject;
        @invocableVariable(required=true)
        public String opprettetAv;
        @invocableVariable
        public String aktoerid;
        @invocableVariable
        public String fnr;
        @invocableVariable
        public String orgnr;
        @invocableVariable
        public String tema;
        @invocableVariable(required=true)
        public Boolean konfidentiellt;
        @invocableVariable
        public String dokumentasjonId;

        public ArchivePostWrapper() {
        }
        @TestVisible
        public ArchivePostWrapper(
            SObject archiveObject,
            String opprettetAv,
            String aktoerid,
            String fnr,
            String orgnr,
            String tema,
            Boolean konfidentiellt,
            String dokumentasjonId
        ) {
            this.archiveObject = archiveObject;
            this.opprettetAv = opprettetAv;
            this.aktoerid = aktoerid;
            this.fnr = fnr;
            this.orgnr = orgnr;
            this.tema = tema;
            this.konfidentiellt = konfidentiellt;
            this.dokumentasjonId = dokumentasjonId;
        }
    }
}