force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_From_Contact__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/classes/CRM_ThreadPdfController_Test.cls
@isTest
public class CRM_ThreadPdfController_Test {
    @TestSetup
    static void makeData() {
        Id contactId = (Id) CRM_HENV_TestDataFactory.createRecord(new Contact()).get('Id');
        Id threadId = (Id) CRM_HENV_TestDataFactory.createRecord(new Thread__c(CRM_Contact__c = contactId)).get('Id');
        CRM_HENV_TestDataFactory.createRecord(
            new Message__c(CRM_Thread__c = threadId, CRM_From_Contact__c = contactId)
        );
    }

    @isTest
    static void testPdfController() {
        PageReference pageRef = Page.CRM_Thread_PDF;
        Test.setCurrentPage(pageRef);
        Id threadId = [SELECT Id FROM Thread__c LIMIT 1].Id;

        ApexPages.currentPage().getParameters().put('Id', threadId);
        ApexPages.StandardController stdThread = new ApexPages.StandardController(new Thread__c(Id = threadId));

        CRM_ThreadPdfController pdfController = new CRM_ThreadPdfController(stdThread);
        System.assert(pdfController.threadMessages.size() > 0);
    }
}