force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_API_Reference__c.field-meta.xml
<CustomField>
    <fullName>CRM_API_Reference__c</fullName>
    <description>Record reference that is exposed via API</description>
    <externalId>true</externalId>
    <label>API Reference</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_Thread_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread_Type__c</fullName>
    <label>Thread Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEFAULT</fullName>
                <default>true</default>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>STB</fullName>
            </value>
            <value>
                <fullName>AAREG_EXP</fullName>
            </value>
            <value>
                <fullName>AAREG_INT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/henvendelse-cache/classes/helpers/ThreadCacheFilterHelper.cls
public without sharing class ThreadCacheFilterHelper {
    private static LoggerUtility logger = new LoggerUtility('HenvendelseCaching');

    public static List<CacheHenvendelseEvent> getCacheEvents(
        Set<Id> threadIds
    ) {
        List<CacheHenvendelseEvent> threadsToBeCached = new List<CacheHenvendelseEvent>();
        List<String> threadTypes = new List<String>{ 'STO', 'STB', 'CHAT', 'BTO' };
                    for (Thread__c thread : [
                        SELECT
                            CRM_Account__r.CRM_Person__r.INT_ActorId__c,
                            CRM_API_Reference__c
                        FROM Thread__c
                        WHERE Id IN :threadIds
                        AND CRM_Thread_Type__c in :threadTypes
                    ]) {
                        if (
                            thread.CRM_Account__r.CRM_Person__r.INT_ActorId__c != null &&
                            thread.CRM_API_Reference__c!= null
                        ) {
                            threadsToBeCached.add(
                                new CacheHenvendelseEvent(
                                    thread.CRM_Account__r.CRM_Person__r.INT_ActorId__c,
                                    thread.CRM_API_Reference__c
                                )
                            );
                        }
                    }
                    return threadsToBeCached;
    }

    public static Set<Id> getThreadIdsByMessages(List<Message__c> messages) {
        ModiaIntegrationUser modiaIntegrationUser = new ModiaIntegrationUser();
        Set<Id> threadIds = new Set<Id>();

        for (Message__c msg : messages) {
            //Only cache records created by Salesforce internal users
            if (msg.LastModifiedById != modiaIntegrationUser.UserId) {
                threadIds.add(msg.CRM_Thread__c);
            }
        }

        return threadIds;
    }
}