force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>CRM_Message_Text__c</fullName>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Read__c.field-meta.xml
<CustomField>
    <fullName>CRM_Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_Thread_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread_Type__c</fullName>
    <label>Thread Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEFAULT</fullName>
                <default>true</default>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>STB</fullName>
            </value>
            <value>
                <fullName>AAREG_EXP</fullName>
            </value>
            <value>
                <fullName>AAREG_INT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/henvendelse-cache/classes/handlers/MessageCacheHandlerTest.cls
@IsTest
public class MessageCacheHandlerTest {
    @TestSetup
    private static void makeData() {
        User experienceCloudUser = (User) CRM_HENV_TestDataFactory.createExperienceCloudUser(); //New Person Account is also created
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;

        CRM_HENV_TestDataFactory.createRecord(
            new Thread__c(
                CRM_Account__c = accountId,
                CRM_Thread_Type__c = 'STO',
                OwnerId = experienceCloudUser.Id
            )
        );
    }

    @IsTest
    static void shouldPublishEventWhenMessageIsCreatedByInternalUser() {
        Id threadId = [SELECT Id FROM Thread__c LIMIT 1].Id;
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        Test.startTest();
        CRM_HENV_TestDataFactory.createRecord(
            new Message__c(
                CRM_Thread__c = threadId,
                CRM_Message_Text__c = 'Test'
            )
        );
        Test.stopTest();

        Assert.areEqual(
            1,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='INFO']
        );

        Assert.areEqual(
            0,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='ERROR']
        );
    }

    @IsTest
    static void shouldPublishEventWhenMessageIsCreatedByExperienceCloudUser() {
        Id threadId = [SELECT Id FROM Thread__c LIMIT 1].Id;
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        User experienceCloudUser = [
            SELECT Id
            FROM User
            WHERE AccountId = :accountId
        ];
        Test.startTest();
        System.runAs(experienceCloudUser) {
            Message__c msg = new Message__c(
                CRM_Thread__c = threadId,
                CRM_Message_Text__c = 'Test'
            );
            insert msg;
        }
        Test.stopTest();

        Assert.areEqual(
            1,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='INFO']
        );

        Assert.areEqual(
            0,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='ERROR']
        );
    }

    @IsTest
    static void shouldPublishEventWhenMessageIsUpdatedByInternalUser() {
        Id threadId = [SELECT Id FROM Thread__c LIMIT 1].Id;
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        Message__c msg = (Message__c) CRM_HENV_TestDataFactory.createRecord(
            new Message__c(
                CRM_Thread__c = threadId,
                CRM_Message_Text__c = 'Test'
            )
        );

        Test.startTest();
        msg.CRM_Read__c = true;
        update msg;
        Test.stopTest();

        Assert.areEqual(
            2,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='INFO']
        );

        Assert.areEqual(
            0,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='ERROR']
        );
    }

    @IsTest
    static void shouldPublishEventWhenMessageIsUpdatedByExperienceCloudUser() {
        Id threadId = [SELECT Id FROM Thread__c LIMIT 1].Id;
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        Message__c msg = (Message__c) CRM_HENV_TestDataFactory.createRecord(
            new Message__c(
                CRM_Thread__c = threadId,
                CRM_Message_Text__c = 'Test'
            )
        );

        User experienceCloudUser = [
            SELECT Id
            FROM User
            WHERE AccountId = :accountId
        ];
        Test.startTest();
        System.runAs(experienceCloudUser) {
            msg.CRM_Read__c = true;
            update msg;
        }

        Test.stopTest();

        Assert.areEqual(
            2,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='INFO']
        );

        Assert.areEqual(
            0,
            [SELECT COUNT() FROM Application_Log__c WHERE Log_Level__c='ERROR']
        );
    }
}