force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_External_Message__c.field-meta.xml
<CustomField>
    <fullName>CRM_External_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_Ident_Formula__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_Ident_Formula__c</fullName>
    <description>For messages migrated that were sent from NAV employees without a Salesforce user, the CRM_From_Ident__c field will store the from information. Messages created in Salesforce will be connected to either a community user or internal user. Returns the external users actor id if the message is from external.</description>
    <formula>IF( CRM_From__c != null,
    (IF( CRM_From__r.ContactId != null,
		CRM_From__r.Contact.Account.CRM_Person__r.INT_ActorId__c,
		CRM_From__r.CRM_NAV_Ident__c 
	)),
	CRM_From_Ident__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>From Ident Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_NAV_Unit__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_NAV_Unit__c</fullName>
    <description>NAV unit number of the user sending the message</description>
    <externalId>true</externalId>
    <label>From NAV Unit</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/API/classes/RestServices/API-wrappers/CRM_MessageFrom.cls
global class CRM_MessageFrom {
    global enum IDENT_TYPES {
        NAVIDENT,
        AKTORID
    }

    global String identType;
    global String ident;
    global String navEnhet;

    global CRM_MessageFrom() {
    }

    global CRM_MessageFrom(Message__c message) {
        this.identType = message.CRM_External_Message__c == true
            ? CRM_MessageFrom.IDENT_TYPES.AKTORID.name()
            : CRM_MessageFrom.IDENT_TYPES.NAVIDENT.name();
        this.ident = message.CRM_From_Ident_Formula__c;
        this.navEnhet = message.CRM_From_NAV_Unit__c;
    }
}