force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_External_Message__c.field-meta.xml
<CustomField>
    <fullName>CRM_External_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From__c.field-meta.xml
<CustomField>
    <fullName>CRM_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Messages1awlkdjaw</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_Label__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_Label__c</fullName>
    <label>From Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>CRM_Message_Text__c</fullName>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Read__c.field-meta.xml
<CustomField>
    <fullName>CRM_Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Recipient__c.field-meta.xml
<CustomField>
    <fullName>CRM_Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Message</fullName>
                <default>true</default>
                <label>Message</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/core-functionality/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_From__c.field-meta.xml
<CustomField>
    <fullName>CRM_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Thread_From</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_isPublic__c.field-meta.xml
<CustomField>
    <fullName>CRM_isPublic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_Number_of_External_Messages__c.field-meta.xml
<CustomField>
    <fullName>CRM_Number_of_External_Messages__c</fullName>
    <label>Number of External Messages</label>
    <summaryFilterItems>
        <field>Message__c.CRM_External_Message__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Message__c.CRM_Thread__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_Recipient__c.field-meta.xml
<CustomField>
    <fullName>CRM_Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Thread_Recipient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_Related_Object__c.field-meta.xml
<CustomField>
    <fullName>CRM_Related_Object__c</fullName>
    <label>Related Object</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/classes/CRM_MessageHelper.cls
/**
 * Helper class for the Messaging solution
 * @Author Lars Petter Johnsen
 * @Date 20.05.2021
 */
public with sharing class CRM_MessageHelper {
    @AuraEnabled(cacheable=true)
    public static String getRecordObjectType(Id recordId) {
        String objectType = recordId.getSObjectType().getDescribe().getName();
        return objectType;
    }

    @AuraEnabled(cacheable=true)
    public static List<Thread__c> getThreadsCollection(Id recordId, Boolean singleThread) {
        if (singleThread == false) {
            return getThreads(recordId);
        } else {
            List<Thread__c> tList = new List<Thread__c>();
            tList.add(getSingleThread(recordId));
            return tList;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Thread__c> getThreads(Id recordId) {
        Id currentUser = UserInfo.getUserId();

        List<Thread__c> threadList;
        try {
            threadList = [
                SELECT
                    Id,
                    CRM_From__c,
                    CRM_From__r.FirstName,
                    CRM_From__r.LastName,
                    CRM_Recipient__r.FirstName,
                    CRM_Recipient__r.LastName,
                    CRM_isPublic__c,
                    CRM_Number_of_External_Messages__c,
                    CRM_Related_Object__c
                FROM Thread__c
                WHERE
                    CRM_Related_Object__c = :recordId
                    AND (CRM_From__c = :currentUser
                    OR CRM_Recipient__c = :currentUser)
            ];
        } catch (Exception e) {
        }
        return threadList;
    }
    @AuraEnabled(cacheable=true)
    public static Thread__c getSingleThread(Id recordId) {
        try {
            Thread__c t = [
                SELECT
                    Id,
                    CRM_From__c,
                    CRM_From__r.FirstName,
                    CRM_From__r.LastName,
                    CRM_Recipient__r.FirstName,
                    CRM_Recipient__r.LastName,
                    CRM_isPublic__c,
                    CRM_Number_of_External_Messages__c,
                    CRM_Related_Object__c
                FROM Thread__c
                WHERE CRM_isPublic__c = TRUE AND CRM_Related_Object__c = :recordId
                LIMIT 1
            ];

            return t;
        } catch (Exception e) {
            return null;
        }
    }
    @AuraEnabled
    public static void createThread(Id recordId) {
        Thread__c newThread = new Thread__c();
        newThread.CRM_isPublic__c = true;
        newThread.CRM_Related_Object__c = recordId;
        insert newThread;
    }

    @AuraEnabled(cacheable=true)
    public static List<Message__c> getMessagesFromThread(Id threadId) {
        try {
            List<Message__c> msgList = [
                SELECT
                    Id,
                    CRM_Message_Text__c,
                    CRM_Type__c,
                    CreatedDate,
                    CRM_From__c,
                    CRM_From_Label__c,
                    CRM_From__r.FirstName,
                    CRM_From__r.LastName,
                    CRM_External_Message__c
                FROM Message__c
                WHERE CRM_Thread__c = :threadId
                ORDER BY CreatedDate ASC
            ];
            return msgList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static string getUserLisenceType(Id userId) {
        try {
            String userLicenseType = [SELECT UserType FROM User WHERE Id = :userId LIMIT 1].UserType;
            return userLicenseType;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    /**
     * Method for marking unread messages - called onload fromt the end user perspective. Does only represent customer read.
     * @Lars Petter Johnsen
     * @Date 31052021
     */
    @AuraEnabled
    public static void markAsRead(Id threadId) {
        List<Message__c> msgList = [SELECT Id FROM Message__c WHERE CRM_Read__c = FALSE AND CRM_Thread__c = :threadId];
        for (Message__c msg : msgList) {
            msg.CRM_Read__c = true;
        }
        update msgList;
    }
}