force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/CRM_API_Reference__c.field-meta.xml
<CustomField>
    <fullName>CRM_API_Reference__c</fullName>
    <description>Record reference that is exposed via API</description>
    <externalId>true</externalId>
    <label>API Reference</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/core-functionality/objects/Message__c/fields/CRM_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Event_Type__c</fullName>
    <description>If message is an event, this field describe the type of event</description>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CRM_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>END_OF_CHAT</fullName>
            </value>
            <value>
                <fullName>UNIT_TRANSFER</fullName>
            </value>
            <value>
                <fullName>QUEUE_TRANSFER</fullName>
            </value>
            <value>
                <fullName>JOURNAL</fullName>
            </value>
            <value>
                <fullName>INTERNAL_MESSAGE</fullName>
            </value>
            <value>
                <fullName>EXTERNAL_MESSAGE</fullName>
            </value>
            <value>
                <fullName>REDACTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_External_Message__c.field-meta.xml
<CustomField>
    <fullName>CRM_External_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_Ident_Formula__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_Ident_Formula__c</fullName>
    <description>For messages migrated that were sent from NAV employees without a Salesforce user, the CRM_From_Ident__c field will store the from information. Messages created in Salesforce will be connected to either a community user or internal user. Returns the external users actor id if the message is from external.</description>
    <formula>IF( CRM_From__c != null,
    (IF( CRM_From__r.ContactId != null,
		CRM_From__r.Contact.Account.CRM_Person__r.INT_ActorId__c,
		CRM_From__r.CRM_NAV_Ident__c 
	)),
	CRM_From_Ident__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>From Ident Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_From_NAV_Unit__c.field-meta.xml
<CustomField>
    <fullName>CRM_From_NAV_Unit__c</fullName>
    <description>NAV unit number of the user sending the message</description>
    <externalId>true</externalId>
    <label>From NAV Unit</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_HenvendelseId__c.field-meta.xml
<CustomField>
    <fullName>CRM_HenvendelseId__c</fullName>
    <description>Reference to unique henvendelse ID which is the kafka message key</description>
    <externalId>true</externalId>
    <label>Henvendelse ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>CRM_Message_Text__c</fullName>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Read__c.field-meta.xml
<CustomField>
    <fullName>CRM_Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Sent_date__c.field-meta.xml
<CustomField>
    <fullName>CRM_Sent_date__c</fullName>
    <label>Sent date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Thread__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread__c</fullName>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CRM_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Message</fullName>
                <default>true</default>
                <label>Message</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/API/classes/RestServices/Selectors/CRM_MessageSelector.cls
public inherited sharing class CRM_MessageSelector extends CRM_ApiSelector {
    public CRM_MessageSelector() {
        super(false);
    }

    /**
     * @description: Returns the default conditions for message to be returnned in the API
     * @author Stian Ruud Schikora | 01-31-2022
     * @return String
     **/
    public String getApiConditions() {
        return 'CRM_Type__c IN (\'Message\',\'Info\', ,\'Event\')';
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Message__c.CRM_Type__c,
            Message__c.CRM_HenvendelseId__c,
            Message__c.CRM_Read__c,
            Message__c.CRM_Thread__c,
            Message__c.CRM_Message_Text__c,
            Message__c.Id,
            Message__c.CRM_Sent_Date__c,
            Message__c.CRM_Read_Datetime__c,
            Message__c.CRM_External_Message__c,
            Message__c.CRM_From_Ident_Formula__c,
            Message__c.CRM_From_NAV_Unit__c,
            Message__c.CRM_API_Reference__c,
            Message__c.CRM_Sensitive_Information__c,
            Message__c.CRM_Event_Type__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Message__c.sObjectType;
    }

    public List<Message__c> selectById(Set<Id> idSet) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id in :idSet AND ' + getApiConditions());
        return (List<Message__c>) Database.query(query.toSOQL());
    }

    public List<Message__c> selectByApiReference(List<String> refSet) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('CRM_API_Reference__c in :refSet AND ' + getApiConditions());
        return (List<Message__c>) Database.query(query.toSOQL());
    }
}